# Generated by Django 3.1 on 2020-08-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contactvalidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactValidate',
        ),
    ]
